### ISSUE TITLE
Advisory: is it possible to specify a variable type?

### ISSUE THREAD

**Issue by sebastiankirsch** [tenpureto/tenpureto#169]
We have some variables that are numbers. Is it possible for Tenpureto to validate such variables upon entering them?

**Comment by rtimush** [comment]
It is not possible at the moment, but should be relatively easy to add, probably with something like this in `.template.yaml`:
```yaml
variables:
  foo:
    value: 123123123
    pattern: [0-9]{8} # regexps look like the easiest way to represent the constraint
```
